"""empty message

Revision ID: 132ce77ea15b
Revises: 
Create Date: 2022-03-17 20:06:38.654294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '132ce77ea15b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=80), nullable=False),
    sa.Column('f_name', sa.String(length=80), nullable=False),
    sa.Column('l_name', sa.String(length=80), nullable=False),
    sa.Column('m_name', sa.String(length=80), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=8), nullable=False),
    sa.Column('phonenum', sa.Integer(), nullable=False),
    sa.Column('dob', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('pri', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    # ### end Alembic commands ###
