"""empty message

Revision ID: 3a3eca7774e4
Revises: d3f3f5d70cb4
Create Date: 2022-03-17 21:26:23.590030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a3eca7774e4'
down_revision = 'd3f3f5d70cb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('phonenum', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'phonenum')
    # ### end Alembic commands ###
