"""empty message

Revision ID: 4b8a5e4aa443
Revises: bfb7a023f8c9
Create Date: 2022-04-12 15:12:57.001142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b8a5e4aa443'
down_revision = 'bfb7a023f8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archive_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('f_name', sa.String(length=100), nullable=False),
    sa.Column('l_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phonenum', sa.String(length=80), nullable=False),
    sa.Column('date_attended', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('archive_list')
    # ### end Alembic commands ###
