"""empty message

Revision ID: 7ad42f6f8999
Revises: 960f407e0448
Create Date: 2022-04-11 16:51:48.449875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ad42f6f8999'
down_revision = '960f407e0448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('dates', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'dates')
    # ### end Alembic commands ###
