"""empty message

Revision ID: 817e04f0b733
Revises: cfa494d9a8e8
Create Date: 2022-04-12 16:24:26.878875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '817e04f0b733'
down_revision = 'cfa494d9a8e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archive_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('f_name', sa.String(length=100), nullable=False),
    sa.Column('l_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phonenum', sa.String(length=80), nullable=False),
    sa.Column('date_attended', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('archive_list')
    # ### end Alembic commands ###
