"""empty message

Revision ID: b07f2efd76bf
Revises: 68aa269f8ad0
Create Date: 2022-04-11 16:42:03.755774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b07f2efd76bf'
down_revision = '68aa269f8ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'date')
    # ### end Alembic commands ###
