"""empty message

Revision ID: bfb7a023f8c9
Revises: 1f9af88abc70
Create Date: 2022-04-11 22:09:16.255193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfb7a023f8c9'
down_revision = '1f9af88abc70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendee_list', sa.Column('f_name', sa.String(length=100), nullable=False))
    op.add_column('attendee_list', sa.Column('l_name', sa.String(length=100), nullable=False))
    op.add_column('attendee_list', sa.Column('email', sa.String(length=120), nullable=False))
    op.add_column('attendee_list', sa.Column('phonenum', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendee_list', 'phonenum')
    op.drop_column('attendee_list', 'email')
    op.drop_column('attendee_list', 'l_name')
    op.drop_column('attendee_list', 'f_name')
    # ### end Alembic commands ###
