"""empty message

Revision ID: c96c42b70d21
Revises: 3a3eca7774e4
Create Date: 2022-03-17 22:10:52.342164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c96c42b70d21'
down_revision = '3a3eca7774e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('date_added', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'date_added')
    # ### end Alembic commands ###
