"""empty message

Revision ID: d3f3f5d70cb4
Revises: 132ce77ea15b
Create Date: 2022-03-17 21:25:57.870482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3f3f5d70cb4'
down_revision = '132ce77ea15b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'phonenum')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('phonenum', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
